
# git log zh_CN and pip warning
export LESSCHARSET=utf-8
export PIP_DISABLE_ROOT_WARNING=1

# mpich toolkit
export MPI_HOME=/root/mpich
export LD_LIBRARY_PATH=${MPI_HOME}/lib:$LD_LIBRARY_PATH
export PATH=${MPI_HOME}/bin:$PATH

# ascend toolkit
export ASCEND_PATH=/usr/local/Ascend

# ascend toolkit
export ASCEND_HOME=${ASCEND_PATH}/ascend-toolkit/latest
export LD_LIBRARY_PATH=${ASCEND_HOME}/lib64:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=${ASCEND_HOME}/aarch64-linux/lib64:$LD_LIBRARY_PATH
export PATH=${ASCEND_HOME}/compiler/ccec_compiler/bin/:${PATH}
if [ -f ${ASCEND_PATH}/ascend-toolkit/set_env.sh ]; then
    source ${ASCEND_PATH}/ascend-toolkit/set_env.sh
fi

# ascend driver
export DRIVER_HOME=${ASCEND_PATH}/driver
export LD_LIBRARY_PATH=${DRIVER_HOME}/lib64:$LD_LIBRARY_PATH
export PATH=${DRIVER_HOME}/tools:${PATH}
if [ -f ${DRIVER_HOME}/bin/setenv.bash ]; then
    source ${DRIVER_HOME}/bin/setenv.bash
fi

# ascend nnae
export NNAE_HOME=${ASCEND_PATH}/nnae
if [ -f ${NNAE_HOME}/set_env.sh ]; then
    source ${NNAE_HOME}/set_env.sh
fi

# ascend nnrt
export NNRT_HOME=${ASCEND_PATH}/nnrt
if [ -f ${NNRT_HOME}/set_env.sh ]; then
    source ${NNRT_HOME}/set_env.sh
fi

# ascend tbe
export ASCEND_OPP_PATH=${ASCEND_HOME}/opp
export TBE_IMPL_PATH=${ASCEND_OPP_PATH}/built-in/op_impl/ai_core/tbe
export PYTHONPATH=${TBE_IMPL_PATH}:${PYTHONPATH}

# add library preload
export LD_PRELOAD=/usr/lib/aarch64-linux-gnu/libGLdispatch.so.0
